### ISSUE TITLE
Setting a Logo

### ISSUE THREAD

**Issue by BamItsPixel** [guileen/node-sendmail#36]
Is it possible to set a "profile picture" or logo that is sent with the emails?
If it is, how would I go about doing it?

Thank you!

**Comment by GreenPioneer** [comment]
@BamItsPixel  Im not sure. Never tried doing it.

**Comment by Geex-Renzo** [comment]
@GreenPioneer I just looked up the [properties Mailcomposer accepts](https://nodemailer.com/extras/mailcomposer/#e-mail-message-fields), can't find it there.
@BamItsPixel Are you sure that is part of an email send and not your email client looking up the profile picture from your contacts?  
If not, can you look up the mail specs where it's listed?

**Comment by GreenPioneer** [comment]
@BamItsPixel did you ever find anything on this ?

@Geex-Renzo  is this feature worth it ?

**Comment by Geex-Renzo** [comment]
@GreenPioneer I've did some research and I couldn't find anything else than "A profile picture will show up if you have the sender in you contacts or your mail provider (like Gmail) has their email address on their server and they've set a profile picture"

@BamItsPixel Other than the above, do you know more about this? Because otherwise, we're going to close this Issue, as it's not possible (yet?)

**Comment by BamItsPixel** [comment]
@Geex-Renzo I think you might be right that it isn't possible. The logos that I've been seeing in inboxes are probably just vendor specific features.
