### ISSUE TITLE
Getting unexpected token error with this new release 1.2.0

### ISSUE THREAD

**Issue by rachitsm** [guileen/node-sendmail#39]
I am getting unexpected token error..
(function (exports, require, module, __filename, __dirname) { const {createConnection} = require('net');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

I am including the module as var sendmail = require('sendmail')(); 

However, when I downgraded and installed version 1.1.1 it worked fine for me. Can someone look into this. 

Thanks.

**Comment by rachitsm** [comment]
Seems like sendmail.js changed 
Release 1.2.0 -
   const {createConnection} = require('net');
   const {resolveMx} = require('dns');
   const {DKIMSign} = require('dkim-signer');
   const CRLF = '\r\n';

Release 1.1.1 - 
   var tcp = require('net');
   var dns = require('dns');
   var CRLF = '\r\n';

**Comment by GreenPioneer** [comment]
@rachitsm  what version of node are you running ?

**Comment by rachitsm** [comment]
v4.4.5

**Comment by GreenPioneer** [comment]
Go Check out http://node.green/#ES2015-syntax-destructuring--parameters 

That version of node does not support  our code

in moving to 1.2  we dont support versions of node lower than 6 
` "node": ">=6.0.0"`

@Geex-Renzo @guileen That begs the question do we need to push a patch out for 1.2.1 and move back to ES5? Then make a new release on 2.0.0 to push ES6? I asked because I realize this is a breaking changed we pushed for older node users and this should have been a major version technically.

**Comment by rachitsm** [comment]
@GreenPioneer Thanks a lot for quick response on this. Appreciate it.
