### ISSUE TITLE
1.2.0 breaks apps using node 4.X

### ISSUE THREAD

**Issue by glenwinters** [guileen/node-sendmail#42]
My project broke because I was using `^1.1.1` for `sendmail` in my `package.json` and auto-upgraded to 1.2.0. I'm using 4.X and 1.2.0 introduced ES2015 syntax that doesn't work on 4.X. It seems like introducing ES2015 should be part of a major version, not a minor version. Is there an assumption that you have to be using node 6.X to use this library? Perhaps that should be stated somewhere.

**Comment by GreenPioneer** [comment]
I agree with you that it should be stated somewhere.

I don't think there is an assumption of `"you have to be using node 6.X to use this library."` Because the old version works just fine still. 

[Updated sendmail.js to ES2015 - Commit](https://github.com/guileen/node-sendmail/commit/5ca6f68a382a9f93191de2ced359f87c8fd44e6b#diff-89bfb32a11118ff54ed0c6f01fc1cb93)

Regardless,  @glenwinters  I think you made a good point we should/could do going forward when we update

Sorry for the late response

**Comment by glenwinters** [comment]
Thanks for the reply! It would be helpful to add "Converted to ES2015" under version 1.2. You can go ahead and close this issue.

**Comment by GreenPioneer** [comment]
updated @glenwinters  - https://github.com/guileen/node-sendmail/blob/master/Readme.md
